# Dependabot configuration for Shell-Lock
# This will automatically check for security updates to GitHub Actions

version: 2
updates:
  # Monitor GitHub Actions for security updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "security"
      include: "scope"

  # Monitor any npm dependencies (if added in the future)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
