name: 🔐 Security Vulnerability Report
description: Report a security vulnerability in Shell-Lock
title: "[SECURITY] "
labels: ["security", "vulnerability", "priority-high"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report
        
        **IMPORTANT**: If this is a critical security vulnerability that could lead to immediate harm, 
        please report it privately via email instead of creating a public issue.
        
        Thank you for helping to keep Shell-Lock secure!

  - type: checkboxes
    id: severity
    attributes:
      label: Vulnerability Severity
      description: Select the severity level (choose one)
      options:
        - label: 🔴 Critical - Immediate risk of credential exposure or system compromise
        - label: 🟠 High - Potential for privilege escalation or data breach
        - label: 🟡 Medium - Security weakness that could be exploited under specific conditions
        - label: 🟢 Low - Minor security improvement or hardening opportunity

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of Shell-Lock is affected?
      options:
        - Credential storage (secure-cred)
        - GitHub CLI wrapper (gh-secure)
        - Shell configuration hardening
        - Backup/recovery system
        - SSH key management
        - Integrity monitoring
        - Installation scripts
        - Documentation
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Provide a clear description of the security issue
      placeholder: |
        Describe the vulnerability:
        - What is the security weakness?
        - How could it be exploited?
        - What is the potential impact?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the vulnerability
      placeholder: |
        1. Set up environment...
        2. Execute command...
        3. Observe behavior...
        4. Security issue manifests as...
    validations:
      required: true

  - type: textarea
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: Describe the potential security impact
      placeholder: |
        - What data could be compromised?
        - What systems could be affected?
        - What privileges could be escalated?
        - What is the attack vector?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Provide details about your environment
      placeholder: |
        - OS: (e.g., Ubuntu 22.04, WSL2, macOS)
        - Shell: (e.g., zsh, bash)
        - Shell-Lock version: 
        - Related tools: (e.g., GPG version, GitHub CLI version)
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix (Optional)
      description: If you have ideas for fixing this vulnerability, please share them
      placeholder: |
        Potential mitigation strategies or code fixes...

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm your understanding of responsible disclosure
      options:
        - label: I understand this vulnerability will be handled responsibly
          required: true
        - label: I agree to not publicly disclose details until a fix is available
          required: true
        - label: I have not shared this vulnerability information elsewhere
          required: true
